version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: valhalla-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - valhalla-network
    working_dir: /app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: valhalla-frontend
    ports:
      - "80:80"
    networks:
      - valhalla-network

networks:
  valhalla-network:
    driver: bridge
